server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

database:
  host: "192.168.7.248"
  port: 1521
  username: "LIS_RS"
  password: "LIS_RS"
  service_name: "orclstb"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  auto_migrate: true  # Enable auto-migration for development

logging:
  level: "debug"
  format: "json"
